---
- name: Configure Apache Web Server
  hosts: ubuntu_server
  become: true
  vars:
    package_name: apache2
  vars_files:
    - "/home/kareem/Documents/depi3/lec67/depi_r3/Task3/ansible_vault.yml"
    
  tasks:
    - name: insall apache web server
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt: 
        name: apache2

    - name: Ensuring that apache is running 
      service:
        name: apache2
        state: started

    ## to do configure the apache to listen in port 8080
    ## and restart the apache
    ## use repalce module to replace the port

    - name : Ensuring that apche is lissitning on port 8080
      ansible.builtin.replace:
        path: /etc/apache2/ports.conf
        regexp: 'Listen 80$'
        replace: 'Listen 8080'

    - name: Ensuring apche2 is reloaded 
      service:
        name: apache2.service
        state: reloaded

    

