apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mariadbsvc
  name: mariadbsvc
spec:
  ports:
  - name: 80-3306
    port: 80
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
status:
  loadBalancer: {}
