apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mariadb
  name: mariadb
  namespace: database-server
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mariadb
status:
  loadBalancer: {}
