apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mariadb
  name: mariadb
  namespace: database-server
spec:
  containers:
  - env:
    - name: MARIADB_ROOT_PASSWORD
      value: "12345"
    image: mariadb
    name: mariadb
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
