global:
  scrape_interval: 10s
rule_files:
  - "alert.yaml"
alerting:
  alert_relabel_configs:
  alertmanagers:
    - static_configs:
        - targets:
           - "promalert:9093"
  
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
    metrics_path: /metrics  

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"] 
    metrics_path: /metrics  