volumes:
  prometheus_data:
  alert_manager:
  grafana-storage:

networks:
  monitoring:
  

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.yaml:/etc/prometheus/alert.yaml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/prometheus/'
    ports:
      - "9090:9090"
  promalert:
    image: prom/alertmanager:v0.28.1
    container_name: promalert
    networks:
      - monitoring
    expose:
      - 9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./telegramTK:/etc/alertmanager/telegramTK
  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    expose:
      - "9100"
    networks:
      - monitoring

  haproxy:
    image: haproxy:3.2.4
    container_name: haproxy
    volumes: 
    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring


  grafana:
    image: grafana/grafana:12.2.0-17660687647
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    networks:
      - monitoring